on:
  push:
    branches: [ "main","ci/cd" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: testing

    env:
      PSQL_USERNAME: ${{ secrets.PSQL_USERNAME }}
      PSQL_PASSWORD: ${{ secrets.PSQL_PASSWORD }}
      PSQL_URL: localhost:5432/testing 

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ env.PSQL_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.PSQL_PASSWORD }}
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Wait for PostgreSQL to be ready
      run: |
        docker ps
        i=0
        # Get the container name of the PostgreSQL service
        container_name=$(docker ps --filter "ancestor=postgres" --format "{{.Names}}")
        until docker exec "$container_name" pg_isready -U postgres || [ $i -ge 25 ]; do
          echo "Waiting for PostgreSQL to be ready... ($i/25)"
          i=$((i+1))
          sleep 5
        done

        # If we reached the limit, exit with an error
        if [ $i -ge 25 ]; then
          echo "PostgreSQL did not become ready in time. Exiting..."
          exit 1
        else
          echo "PostgreSQL is ready!"
        fi

    - name: Create the database
      run: |
        container_name=$(docker ps --filter "ancestor=postgres" --format "{{.Names}}")
        docker exec -i "$container_name" psql -U postgres -c "CREATE DATABASE testing;"

    - name: Run migrations or set up the database
      run: |
        # Add any commands needed to set up your database, such as running migrations
        echo "Database setup step (optional)."

    - name: Test with unittest
      run: |
        # Run your tests
        python -m unittest ./server/tests/tests.py
